export const TOKENS = {
  CREATE_USER_PORT: Symbol('CREATE_USER_PORT'),
  CHECK_IN_USER_PORT: Symbol('CHECK_IN_USER_PORT'),
  VALIDATE_USER_PORT: Symbol('VALIDATE_USER_PORT'),
  SIGN_IN_USER_PORT: Symbol('SIGN_IN_USER_PORT'),
};
